name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare ssh key
      run: |
        mkdir $HOME/.ssh
        chmod 700 $HOME/.ssh
        ssh-keyscan grant.mk >> $HOME/.ssh/known_hosts
        echo '${{ secrets.DEPLOY_PRIVATE_KEY }}' > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
    - name: Clone git repo and push to production
      run: |
        git clone https://github.com/creativecoder/thoughtfulmuse.git
        cd thoughtfulmuse
        git remote add dokku ${{ secrets.DEPLOY_REPO }}
        git push dokku master
