---
name: "deploy"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.DEPLOY_REPO }}
          ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
